Fix error message in git fetch

diff --git a/scripts/aur-update b/scripts/aur-update
--- a/scripts/aur-update
+++ b/scripts/aur-update
@@ -144,7 +144,7 @@ echo "Fetching remote changes"
 
 if ! (cd "${WorkDir}" || exit 1; git fetch);
 then
-    echo "Fetching remote changes" >&2
+    echo "Fetching remote changes failed" >&2
     exit 1
 fi
 
